# Generated by Django 2.2.5 on 2020-11-13 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serelia',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
