# Generated by Django 2.2.5 on 2020-11-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='Nama')),
                ('phone', models.TextField(db_column='phone', max_length=200, verbose_name='No HP')),
            ],
            options={
                'verbose_name': 'Kontak',
                'verbose_name_plural': 'Kontak',
                'db_table': 'contact',
            },
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name': 'Variety', 'verbose_name_plural': 'Varietas'},
        ),
        migrations.AlterField(
            model_name='variety',
            name='description',
            field=models.TextField(db_column='description', max_length=200, verbose_name='Deskripsi'),
        ),
    ]
