# Generated by Django 2.2.5 on 2020-11-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0002_auto_20201118_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(db_column='phone', max_length=20, verbose_name='No HP'),
        ),
    ]
