# Generated by Django 2.2.5 on 2020-11-13 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0002_serelia_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serelia',
            name='create_date',
        ),
        migrations.AddField(
            model_name='serelia',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
