# Generated by Django 2.2.5 on 2020-11-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0003_auto_20201114_0041'),
        ('simuliaapp', '0003_auto_20201118_1019'),
    ]

    operations = [
    ]
