# Generated by Django 2.2.5 on 2020-11-18 04:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0004_merge_20201118_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serelia',
            options={'verbose_name': 'Standing Crop Benih', 'verbose_name_plural': 'Standing Crop Benih'},
        ),
        migrations.AlterField(
            model_name='serelia',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Tanggal Laporan'),
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processingid', models.CharField(db_column='processingid', max_length=50, verbose_name='Processing ID')),
                ('in_date', models.DateField(blank=True, db_column='in_date', max_length=100, null=True, verbose_name='Tanggal Masuk')),
                ('weight', models.IntegerField(db_column='weight', default=0, verbose_name='Berat Tongkol')),
                ('source', models.CharField(db_column='source', max_length=100, verbose_name='Asal Benih')),
                ('cp_name', models.TextField(db_column='cp_name', max_length=100, verbose_name='Penanggung Jawab')),
                ('out_date', models.DateField(blank=True, db_column='out_date', max_length=100, null=True, verbose_name='Tanggal Keluar')),
                ('result', models.CharField(db_column='result', max_length=100, verbose_name='Hasil Benih')),
                ('evidence', models.ImageField(upload_to='uploaded/evidence', verbose_name='Upload Image')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simuliaapp.Variety')),
            ],
            options={
                'verbose_name': 'Processing Benih',
                'verbose_name_plural': 'Processing Benih',
                'db_table': 'processing',
            },
        ),
    ]
