# Generated by Django 2.2.5 on 2020-11-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0005_auto_20201118_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing',
            name='weight',
            field=models.IntegerField(db_column='weight', default=0, verbose_name='Berat Tongkol (kg)'),
        ),
        migrations.CreateModel(
            name='Warehousestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.CharField(db_column='stockid', max_length=50, verbose_name='Stock ID')),
                ('start_weight', models.IntegerField(db_column='start_weight', default=0, verbose_name='Stok Awal (kg)')),
                ('out_weight', models.IntegerField(db_column='out_weight', default=0, verbose_name='Keluar (kg)')),
                ('end_weight', models.IntegerField(db_column='end_weight', default=0, verbose_name='Stok Akhir (kg)')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simuliaapp.Variety')),
            ],
            options={
                'verbose_name': 'Stok Gudang PS',
                'verbose_name_plural': 'Stok Gudang PS',
                'db_table': 'warehousestock',
            },
        ),
    ]
