# Generated by Django 2.2.5 on 2020-11-18 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0006_auto_20201118_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name': 'Varietas', 'verbose_name_plural': 'Varietas'},
        ),
        migrations.AddField(
            model_name='processing',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Tanggal Laporan'),
        ),
    ]
