# Generated by Django 2.2.5 on 2020-11-18 06:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0007_auto_20201118_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Tanggal Laporan'),
        ),
        migrations.AlterField(
            model_name='processing',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simuliaapp.Variety', verbose_name='Varietas'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simuliaapp.Variety', verbose_name='Varietas'),
        ),
    ]
