# Generated by Django 2.2.5 on 2020-11-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simuliaapp', '0009_auto_20201118_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processing',
            name='weight',
            field=models.FloatField(db_column='weight', verbose_name='Berat Tongkol (kg)'),
        ),
        migrations.AlterField(
            model_name='serelia',
            name='area',
            field=models.FloatField(db_column='area', verbose_name='Luas Lahan (ha)'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='end_weight',
            field=models.FloatField(db_column='end_weight', verbose_name='Stok Akhir (kg)'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='out_weight',
            field=models.FloatField(db_column='out_weight', verbose_name='Keluar (kg)'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='start_weight',
            field=models.FloatField(db_column='start_weight', verbose_name='Stok Awal (kg)'),
        ),
    ]
